import uuid from 'react-uuid'

const myBooks = [
    {
        id: uuid(),
        title: "월가의 영웅",
        author: "피터린치·존 로스차일드",
        category: "투자",
        coverColor: "#00B7AF",
        textColor: "#181617",
        height: "90%",
        thickness: "50px",
    },
    {
        id: uuid(),
        title: "클린코드",
        author: "로버트 C 마틴",
        category: "개발",
        coverColor: "#FF3011",
        textColor: "#fff",
        height: "80%",
        thickness: "83px",
    },
    {
        id: uuid(),
        title: "소셜온난화",
        author: "찰스 아서",
        category: "투자",
        coverColor: "#FC9994",
        textColor: "#181617",
        height: "89%",
        thickness: "89px",
    },
    {
        id: uuid(),
        title: "PRINCIPLE",
        author: "찰스 아서",
        category: "투자",
        coverColor: "#F98700",
        textColor: "#181617",
        height: "50%",
        thickness: "60px",
    },
    {
        id: uuid(),
        title: "메타 페이스북",
        author: "스티븐레비",
        category: "투자",
        coverColor: "#181617",
        textColor: "#ffffff",
        height: "50%",
        thickness: "120px",
    },
    {
        id: uuid(),
        title: "클린코드",
        author: "로버트 C 마틴",
        category: "개발",
        coverColor: "#FF3011",
        textColor: "#fff",
        height: "80%",
        thickness: "83px",
    },
    {
        id: uuid(),
        title: "소셜온난화",
        author: "찰스 아서",
        category: "투자",
        coverColor: "#FC9994",
        textColor: "#181617",
        height: "89%",
        thickness: "89px",
    },
]

export default myBooks;